sudo: required
services:
  - docker

before_install:
  - docker build -t ganeshgaitonde/docker-react -f Dockerfile.dev .

script:
  - docker run ganeshgaitonde/docker-react npm run stop

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "/elasticbeanstalk-us-east-2-041394826900 "
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
